CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a web application', 1, 'Using JavaScript', '2022-06-13');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make an App', 1, 'Using Dart', '2022-06-14');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a desktop App', 2, 'Using C++', '2022-06-15');

-- INSERT TASK DATA
INSERT INTO tasks(name, done, projectID)
    VALUES('Download Vuejs', false, 1);

INSERT INTO tasks(name, done, projectID)
    VALUES('Create UI web', false, 1);

INSERT INTO tasks(name, done, projectID)
    VALUES('Download Flutter', false, 2);

INSERT INTO tasks(name, done, projectID)
    VALUES('Design UI', false, 2);